### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by walsha2** [Milad-Akarie/skeletonizer#15]
# Description

@Milad-Akarie Continuously getting this error on `0.8.0`. Downgrading to `0.7.0` resolves this `null` check error.

The error happens when one `Skeletonizer` widget has a **nested child** that also has a `Skeletonizer` wrapped widget. At least this is how I was able to reproduce the issue. 

Refactoring my code solved the issue, but figured I would report this item in case it was an unexpected bug. Since it does not happen on `0.7.0`, I assume it may be an accidental regression?

# Error Trace

```dart
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following _TypeError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was:
  _Skeletonizer

When the exception was thrown, this was the stack:
#0      _RenderSkeletonBase.paint (package:skeletonizer/src/rendering/render_skeletonizer.dart:201:19)
#1      SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#2      RenderSliverSingleBoxAdapter.paint (package:flutter/src/rendering/sliver.dart:1828:15)
#3      SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#4      RenderSliverEdgeInsetsPadding.paint (package:flutter/src/rendering/sliver_padding.dart:263:15)
#5      SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#6      RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:690:17)
#7      RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:675:7)
#8      SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#9      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#10     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#12     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#13     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#14     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#15     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#16     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#18     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#19     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#20     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#21     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#22     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#24     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:618:11)
#25     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#26     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#27     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#28     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#29     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#31     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#32     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#33     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#35     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#36     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2875:15)
#37     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1040:7)
#38     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#39     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#40     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#41     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#42     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:472:12)
#43     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4755:13)
#44     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#45     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:338:15)
#46     SkeletonizerPaintingContext.paintChild (package:skeletonizer/src/painting/skeletonizer_painting_context.dart:96:11)
#47     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#48     _RenderSkeletonBase.paint (package:skeletonizer/src/rendering/render_skeletonizer.dart:206:11)
#49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#50     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#51     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#52     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:263:7)
#53     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:244:7)
#54     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#56     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#57     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#58     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:472:12)
#59     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4755:13)
#60     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#61     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#62     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#63     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#64     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#65     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#66     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#67     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#68     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#69     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:263:7)
#70     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:244:7)
#71     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#72     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#73     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#74     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#75     RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2555:17)
#76     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#77     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#78     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7756:15)
#79     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#80     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#81     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#82     RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1060:11)
#83     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#84     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#85     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#86     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:263:7)
#87     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:244:7)
#88     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#89     RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2555:17)
#90     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#91     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#92     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#93     RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1060:11)
#94     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#95     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#96     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#97     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:263:7)
#98     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:244:7)
#99     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#100    RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2555:17)
#101    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#102    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#103    _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7756:15)
#104    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#105    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#106    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#107    RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1060:11)
#108    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#109    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#110    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#111    PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:263:7)
#112    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:244:7)
#113    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#114    RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2555:17)
#115    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#116    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#117    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#118    RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1060:11)
#119    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#120    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#121    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#122    PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:263:7)
#123    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:244:7)
#124    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#125    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#126    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#127    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#128    PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:263:7)
#129    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:244:7)
#130    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#131    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#132    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#133    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#134    RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3752:11)
#135    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#136    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#137    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#138    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#139    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#140    _RenderTheaterMixin.paint (package:flutter/src/widgets/overlay.dart:866:15)
#141    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:472:12)
#142    PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:532:7)
#143    _RenderTheater.paint (package:flutter/src/widgets/overlay.dart:1116:38)
#144    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#145    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#146    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#147    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#148    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#149    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#150    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#151    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#152    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2875:15)
#153    RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:410:5)
#154    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#155    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#156    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#157    _RenderInkFeatures.paint (package:flutter/src/material/material.dart:664:11)
#158    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#159    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#160    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#161    RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2049:15)
#162    PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:561:14)
#163    RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2036:21)
#164    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#165    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#166    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2875:15)
#167    RenderFlex.paint (package:flutter/src/rendering/flex.dart:1040:7)
#168    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#169    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#170    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2875:15)
#171    RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:410:5)
#172    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#173    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#174    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#175    _RenderInkFeatures.paint (package:flutter/src/material/material.dart:664:11)
#176    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#177    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#178    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#179    RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2049:15)
#180    PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:561:14)
#181    RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2036:21)
#182    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#183    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#184    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#185    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#186    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#187    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#188    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#189    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#190    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#191    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1144:31)
#192    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:496:19)
#193    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#194    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#195    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#196    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#197    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#198    _invoke (dart:ui/hooks.dart:170:13)
#199    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#200    _drawFrame (dart:ui/hooks.dart:140:31)

The following RenderObject was being processed when the exception was fired: RenderSkeletonizer#3f59e:
  needs compositing
  creator: SkeletonizerRenderObjectWidget ← SkeletonizerScope ← _Skeletonizer ←
    SelectionRegistrarScope ← SelectionContainer ← _FocusInheritedScope ← Focus ← _ActionsScope ←
    Actions ← Listener ← RawGestureDetector ← CompositedTransformTarget ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1083.0, h=720.0)
  layer: OffsetLayer#6c326 DETACHED
  size: Size(1083.0, 720.0)
This RenderObject had the following descendants (showing up to depth 5):
    child: _RenderLayoutBuilder#39cc7 NEEDS-PAINT
      child: RenderLeaderLayer#04fc3 NEEDS-PAINT
        child: RenderPointerListener#f3633 NEEDS-PAINT
          child: RenderFlex#5f5c8 NEEDS-PAINT
            child 1: RenderPadding#45bf0 relayoutBoundary=up1 NEEDS-PAINT
            child 2: RenderRepaintBoundary#b9f0b relayoutBoundary=up1 NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/rendering/layer.dart': Failed assertion: line 877 pos 12: 'picture != null': is not true.
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 3253 pos 12: 'attached': is not true.
Another exception was thrown: Null check operator used on a null value
```

**Comment by alejandrogiubel** [comment]
same here

**Comment by MaTeS72** [comment]
still not fixed

**Comment by Milad-Akarie** [comment]
@bronjham-code @MaTeS72 why using a nested a skeletonizer?

**Comment by bronjham-code** [comment]
> @bronjham-code @MaTeS72зачем использовать вложенный скелетонизатор? это вообще не рекомендуется, чего вы пытаетесь достичь?

in my case, the content of the page is loaded sequentially by several requests, and I display what has been loaded without waiting for complete loading.

**Comment by Milad-Akarie** [comment]
@bronjham-code I fixed the issue in 1.0.1,  I still don't see any point of nested skeletonizers, maybe wrap every section with a skeletonizer without nesting them? Anyway I'm closing this for as fixed.

**Comment by bronjham-code** [comment]
thanks for the solution

**Comment by haakonjacobsen** [comment]
The error is back in v. 1.1.0

**Comment by MaTeS72** [comment]
Try to just use Skeletonizer.zone for parent skeletonizers, that should solve the issue.
