### ISSUE TITLE
Can't find widget by type in widget tests.

### ISSUE THREAD

**Issue by xVemu** [Milad-Akarie/skeletonizer#24]
If you try to find widget by `Skeletonizer` type, it throws an error instead of passing `findsOneWidget` matcher.

<details>
<summary>Code sample</summary>

```dart
void main() {
  testWidgets('skeleton', (driver) async {
    final widget = Skeletonizer(child: Text("test"));

    await driver.pumpWidget(MaterialApp(home: widget));
    expect(find.byType(Skeletonizer, skipOffstage: false), findsOneWidget);
  });
}
```

</details>

<details>
<summary>Stacktrace</summary>

```
Testing started at 12:24 ...

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching candidate
  Actual: _TypeWidgetFinder:<Found 0 widgets with type "Skeletonizer": []>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///C:/Users/kkras/mobile/test/models/base/paging_result_model_test.dart:75:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///C:/Users/kkras/mobile/test/models/base/paging_result_model_test.dart line 75
The test description was:
  skeleton
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: skeleton
```

</details>

**Comment by xVemu** [comment]
Just use `SkeletonizerScope` instead of `Skeletonizer` in `byType`.
